KEYWORDS = [
    "med school admissions",
    "law school prep",
    "student mental health",
    "AI in education",
    "MCAT prep",
    "LSAT prep",
    "restaurants Canada",
    "food brands Canada",
    "clinics Canada",
    "wellness brands Canada",
    "retail chains Canada",
    "local Canadian businesses",
    "medical school admissions",
    "med school debt",
    "physician burnout",
    "residency match",
    "pre-med",
    "student loans",
    "AI in medical education",
    "medical school rankings",
    "personal statement",
    "law school admissions",
    "LSAT",
    "legal tech",
    "AI and law",
    "bar exam",
    "student debt law",
    "legal careers",
    "mental health in law school",
]
